In [1]:
from google.colab import drive 
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [2]:
# Import all the necessary libraries
import csv
import pandas as pd
import numpy as np 
from numpy import random

In [5]:
# Load data from csv file into a pandas dataframe
df_1 = pd.read_csv('gdrive/My Drive/Colab Notebooks/GB_youtube_trending_data.csv')

array = df_1.to_numpy() # Convert the pandas dataframe into a NumPy array

# Loop through each video and get the title, likes, dislikes of each video and write them into a csv file
for i in range(len(array)):
  title = str(array[i][4])
  likes = str(array[i][9])
  dislikes = str(array[i][10])

  with open('gdrive/My Drive/Colab Notebooks/GB_YT_ratings.csv', 'a',encoding='utf-8') as newFile:
    FileWriter = csv.writer(newFile)
    FileWriter.writerow([title, likes, dislikes])

In [6]:
# Merge all the data into a single csv file
data = pd.read_csv('gdrive/My Drive/Colab Notebooks/US_YT_ratings.csv')

data_2 = pd.read_csv('gdrive/My Drive/Colab Notebooks/CA_YT_ratings.csv')

data_3 = pd.read_csv('gdrive/My Drive/Colab Notebooks/GB_YT_ratings.csv')

data_final = pd.concat([data,data_2,data_3])

data_final.to_csv('gdrive/My Drive/Colab Notebooks/All_YT_ratings.csv', encoding='utf-8')

In [7]:
# Sort the titles into ascending order
df_2 = pd.read_csv('gdrive/My Drive/Colab Notebooks/All_YT_ratings.csv')

sum_rating_df = df_2.groupby(["Title"])[["Likes","Dislikes"]].sum()

sum_rating_df.to_csv('gdrive/My Drive/Colab Notebooks/All_YT_ratings_sum.csv', encoding='utf-8')

In [10]:
df_1 = pd.read_csv('gdrive/My Drive/Colab Notebooks/All_YT_ratings_sum.csv')

array = df_1.to_numpy()

# Loop through each video and assign users to each video randomly and calculate the ratio of likes to dislikes for each video
for i in range(len(array)):
  title = str(array[i][0])
  likes = str(array[i][1])
  likes1 = int(array[i][1])
  dislikes = str(array[i][2])
  dislikes1 = int(array[i][2])
  userid = 'user_'+str(random.randint(0,100))

  try:
    if dislikes1 == 0:
      rating = likes1
    else:
      rating = likes1/dislikes1

  except:
    print("Something is not right here!")

  with open('gdrive/My Drive/Colab Notebooks/All_YT_ratings_ratio.csv', 'a',encoding='utf-8') as newFile:
    FileWriter = csv.writer(newFile)
    FileWriter.writerow([userid, title, likes, dislikes, rating])

In [3]:
# Drop rows where either of the column values is zero
df_1 = pd.read_csv('gdrive/My Drive/Colab Notebooks/All_YT_ratings_ratio.csv')

df_2 = df_1.drop(df_1[(df_1.Likes == 0) | (df_1.Dislikes == 0)].index)

df_2.to_csv('gdrive/My Drive/Colab Notebooks/New_ratings.csv', encoding='utf-8')

In [4]:
# Normalize the ratio of likes to dislikes on a scale of 0-10
from sklearn import preprocessing

ratio_videos = pd.read_csv("gdrive/My Drive/Colab Notebooks/New_ratings.csv")
scaler = preprocessing.MinMaxScaler(feature_range=(0, 10))
names = ratio_videos[["Ratio"]]
d = scaler.fit_transform(names)
scaled_df = pd.DataFrame(d, columns=["Mean"])
data_final = pd.concat([ratio_videos, scaled_df], axis = 1, join = 'inner')
scaled_df2 = data_final.loc[data_final["Mean"] > 0 ]
scaled_df2.to_csv('gdrive/My Drive/Colab Notebooks/New_ratings_scaled.csv', encoding='utf-8')

In [ ]:
user_ratings=pd.read_csv('gdrive/My Drive/Colab Notebooks/New_ratings_scaled.csv')

In [6]:
user_ratings_pivot = user_ratings.pivot(index='userID', columns='Title', values='Mean')

print(user_ratings_pivot)

user_ratings_df=user_ratings_pivot

Title    #TeamTrees  $uicideboy$  (G)I-DLE (여자)아이들 (Official YouTube Channel)  \
userID
user_0          NaN          NaN                                          NaN
user_1          NaN          NaN                                          NaN
user_10         NaN          NaN                                          NaN
user_11         NaN          NaN                                          NaN
user_12         NaN          NaN                                          NaN
...             ...          ...                                          ...
user_95         NaN          NaN                                          NaN
user_96         NaN          NaN                                          NaN
user_97         NaN          NaN                                          NaN
user_98         NaN          NaN                                          NaN
user_99         NaN          NaN                                          NaN

Title    10 Downing Street  10 News First  10 Tampa Bay  100 Thieves  \
userID
user_0                 NaN            NaN      0.029645          NaN
user_1                 NaN            NaN           NaN          NaN
user_10                NaN            NaN           NaN          NaN
user_11                NaN            NaN           NaN          NaN
user_12                NaN            NaN           NaN          NaN
...                    ...            ...           ...          ...
user_95                NaN            NaN           NaN          NaN
user_96                NaN            NaN           NaN          NaN
user_97                NaN            NaN           NaN          NaN
user_98                NaN            NaN           NaN          NaN
user_99                NaN            NaN           NaN          NaN

Title    100 Thieves Shorts  100% Pure New Zealand  100% Star Wars  ...  \
userID                                                              ...
user_0                  NaN                    NaN             NaN  ...
user_1                  NaN                    NaN             NaN  ...
user_10                 NaN                    NaN             NaN  ...
user_11                 NaN                    NaN             NaN  ...
user_12                 NaN                    NaN             NaN  ...
...                     ...                    ...             ...  ...
user_95                 NaN                    NaN             NaN  ...
user_96                 NaN                    NaN             NaN  ...
user_97                 NaN                    NaN             NaN  ...
user_98                 NaN                    NaN             NaN  ...
user_99                 NaN                    NaN             NaN  ...

Title    바라던 바다  선미 SUNMI  스브스케이팝 / SBS KPOP  아는형님 Knowingbros  \
userID
user_0      NaN       NaN                NaN               NaN
user_1      NaN       NaN                NaN               NaN
user_10     NaN       NaN                NaN               NaN
user_11     NaN  0.011938                NaN               NaN
user_12     NaN       NaN                NaN               NaN
...         ...       ...                ...               ...
user_95     NaN       NaN                NaN               NaN
user_96     NaN       NaN                NaN               NaN
user_97     NaN       NaN                NaN               NaN
user_98     NaN       NaN                NaN               NaN
user_99     NaN       NaN                NaN               NaN

Title    여자친구 GFRIEND OFFICIAL  영국남자 Korean Englishman  웃웃TwinsFromRussia  \
userID
user_0                     NaN                0.033754                NaN
user_1                     NaN                     NaN                NaN
user_10                    NaN                     NaN                NaN
user_11                    NaN                     NaN                NaN
user_12                    NaN                     NaN                NaN
...                        ...                     ...                ...
user_95                    NaN                     NaN                NaN
user_96                    NaN                     NaN                NaN
user_97                    NaN                     NaN                NaN
user_98                    NaN                     NaN                NaN
user_99                    NaN                     NaN                NaN

Title    채널 NCT DANCE  팩트iN스타 Fact iN Star  픽보이 - Peakboy Official
userID
user_0            NaN                  NaN                     NaN
user_1            NaN                  NaN                     NaN
user_10           NaN                  NaN                     NaN
user_11           NaN                  NaN                     NaN
user_12           NaN                  NaN                     NaN
...               ...                  ...                     ...
user_95           NaN                  NaN                     NaN
user_96           NaN                  NaN                     NaN
user_97           NaN                  NaN                     NaN
user_98      0.033985                  NaN                     NaN
user_99           NaN                  NaN                     NaN

[100 rows x 7303 columns]

In [7]:
# Fill rows with NaN with 0 instead
user_ratings_pivot.fillna(0, inplace=True)
user_ratings_pivot

Title,#TeamTrees,$uicideboy$,(G)I-DLE (여자)아이들 (Official YouTube Channel),10 Downing Street,10 News First,10 Tampa Bay,100 Thieves,100 Thieves Shorts,100% Pure New Zealand,100% Star Wars,...,바라던 바다,선미 SUNMI,스브스케이팝 / SBS KPOP,아는형님 Knowingbros,여자친구 GFRIEND OFFICIAL,영국남자 Korean Englishman,웃웃TwinsFromRussia,채널 NCT DANCE,팩트iN스타 Fact iN Star,픽보이 - Peakboy Official
userID,,,,,,,,,,,,,,,,,,,,,
user_0,0.0,0.0,0.0,0.0,0.0,0.029645,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.033754,0.0,0.000000,0.0,0.0
user_1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
user_10,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
user_11,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.011938,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
user_12,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
user_95,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
user_96,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
user_97,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0
user_98,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.033985,0.0,0.0
user_99,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0

In [8]:
# Import the required libraries 
from scipy.sparse.linalg import svds
import numpy as np

# Decompose the matrix
U, sigma, Vt = svds(user_ratings_pivot)

# Convert sigma into a diagonal matrix
sigma = np.diag(sigma)
print(sigma)

[[ 2.04885372  0.          0.          0.          0.          0.        ]
 [ 0.          2.16345695  0.          0.          0.          0.        ]
 [ 0.          0.          3.42034855  0.          0.          0.        ]
 [ 0.          0.          0.          5.92488853  0.          0.        ]
 [ 0.          0.          0.          0.          7.30658802  0.        ]
 [ 0.          0.          0.          0.          0.         10.00777726]]

In [9]:
avg_ratings = user_ratings_pivot.mean(axis=1)

In [10]:
# Dot product of U and sigma
U_sigma = np.dot(U, sigma)

# Dot product of result and Vt
U_sigma_Vt = np.dot(U_sigma, Vt)

# Add back on the row means contained in avg_ratings
uncentered_ratings = U_sigma_Vt + avg_ratings.values.reshape(-1, 1)

# Create DataFrame of the results
calc_pred_ratings_df = pd.DataFrame(uncentered_ratings, index=user_ratings_df.index,columns=user_ratings_df.columns)

# Print both the recalculated matrix and the original                                    
print(calc_pred_ratings_df)

Title    #TeamTrees  $uicideboy$  (G)I-DLE (여자)아이들 (Official YouTube Channel)  \
userID
user_0     0.000309     0.000309                                     0.000309
user_1     0.000148     0.000148                                     0.000148
user_10    0.000147     0.000147                                     0.000147
user_11    0.000171     0.000171                                     0.000171
user_12    0.000397     0.000397                                     0.000397
...             ...          ...                                          ...
user_95    0.000479     0.000479                                     0.000479
user_96    0.000145     0.000145                                     0.000145
user_97    0.000206     0.000206                                     0.000206
user_98    0.000239     0.000239                                     0.000239
user_99    0.000195     0.000195                                     0.000195

Title    10 Downing Street  10 News First  10 Tampa Bay  100 Thieves  \
userID
user_0            0.000309       0.000309      0.000309     0.000309
user_1            0.000148       0.000148      0.000148     0.000148
user_10           0.000147       0.000147      0.000147     0.000147
user_11           0.000171       0.000171      0.000171     0.000171
user_12           0.000397       0.000397      0.000397     0.000397
...                    ...            ...           ...          ...
user_95           0.000479       0.000479      0.000479     0.000479
user_96           0.000145       0.000145      0.000145     0.000145
user_97           0.000206       0.000206      0.000206     0.000206
user_98           0.000239       0.000239      0.000239     0.000239
user_99           0.000195       0.000195      0.000195     0.000195

Title    100 Thieves Shorts  100% Pure New Zealand  100% Star Wars  ...  \
userID                                                              ...
user_0             0.000309               0.000309        0.000309  ...
user_1             0.000148               0.000148        0.000148  ...
user_10            0.000147               0.000147        0.000147  ...
user_11            0.000171               0.000171        0.000171  ...
user_12            0.000397               0.000397        0.000397  ...
...                     ...                    ...             ...  ...
user_95            0.000479               0.000479        0.000479  ...
user_96            0.000145               0.000145        0.000145  ...
user_97            0.000206               0.000206        0.000206  ...
user_98            0.000239               0.000239        0.000239  ...
user_99            0.000195               0.000195        0.000195  ...

Title      바라던 바다  선미 SUNMI  스브스케이팝 / SBS KPOP  아는형님 Knowingbros  \
userID
user_0   0.000309  0.000309           0.000309          0.000309
user_1   0.000148  0.000148           0.000148          0.000148
user_10  0.000147  0.000147           0.000147          0.000147
user_11  0.000171  0.000171           0.000171          0.000171
user_12  0.000397  0.000397           0.000397          0.000397
...           ...       ...                ...               ...
user_95  0.000479  0.000479           0.000479          0.000479
user_96  0.000145  0.000145           0.000145          0.000145
user_97  0.000206  0.000206           0.000206          0.000206
user_98  0.000239  0.000239           0.000239          0.000239
user_99  0.000195  0.000195           0.000195          0.000195

Title    여자친구 GFRIEND OFFICIAL  영국남자 Korean Englishman  웃웃TwinsFromRussia  \
userID
user_0                0.000309                0.000309           0.000309
user_1                0.000148                0.000148           0.000148
user_10               0.000147                0.000147           0.000147
user_11               0.000171                0.000171           0.000171
user_12               0.000397                0.000397           0.000397
...                        ...                     ...                ...
user_95               0.000479                0.000479           0.000479
user_96               0.000145                0.000145           0.000145
user_97               0.000206                0.000206           0.000206
user_98               0.000239                0.000239           0.000239
user_99               0.000195                0.000195           0.000195

Title    채널 NCT DANCE  팩트iN스타 Fact iN Star  픽보이 - Peakboy Official
userID
user_0       0.000309             0.000309                0.000309
user_1       0.000148             0.000148                0.000148
user_10      0.000147             0.000147                0.000147
user_11      0.000171             0.000171                0.000171
user_12      0.000397             0.000397                0.000397
...               ...                  ...                     ...
user_95      0.000479             0.000479                0.000479
user_96      0.000145             0.000145                0.000145
user_97      0.000206             0.000206                0.000206
user_98      0.000239             0.000239                0.000239
user_99      0.000195             0.000195                0.000195

[100 rows x 7303 columns]

In [11]:
# Sort the ratings of User 8 from high to low
user_8_ratings = calc_pred_ratings_df.loc['user_8',:].sort_values(ascending=False)

print(user_8_ratings.head())

Title
Entertainment Weekly    0.000099
Bronzo                  0.000099
SOS 5                   0.000099
Physics Girl            0.000099
JiDion                  0.000099
Name: user_8, dtype: float64